# Google Cloud Build Configuration
# 고성능 빌드를 위한 최적화된 설정

steps:
  # ========================================
  # 1. ENVIRONMENT SETUP
  # ========================================
  - name: 'gcr.io/cloud-builders/git'
    id: 'setup-git'
    args: ['clone', 'https://github.com/flutter/flutter.git', '-b', '3.16.0', '/workspace/flutter']

  - name: 'ubuntu'
    id: 'setup-flutter-path'
    env:
      - 'PATH=/workspace/flutter/bin:$$PATH'
    script: |
      export PATH="/workspace/flutter/bin:$$PATH"
      flutter doctor -v
      flutter --version

  # ========================================
  # 2. DEPENDENCY MANAGEMENT
  # ========================================
  - name: 'gcr.io/cloud-builders/dart'
    id: 'get-dependencies'
    env:
      - 'PATH=/workspace/flutter/bin:$$PATH'
    script: |
      export PATH="/workspace/flutter/bin:$$PATH"
      flutter pub get
      flutter pub deps

  # ========================================
  # 3. CODE QUALITY CHECKS
  # ========================================
  - name: 'gcr.io/cloud-builders/dart'
    id: 'code-analysis'
    env:
      - 'PATH=/workspace/flutter/bin:$$PATH'
    script: |
      export PATH="/workspace/flutter/bin:$$PATH"

      # Static analysis
      flutter analyze --fatal-infos --fatal-warnings

      # Code formatting check
      dart format --set-exit-if-changed .

      # Import sorting check
      flutter pub run import_sorter:main --check-only

  # ========================================
  # 4. TESTING SUITE
  # ========================================
  - name: 'gcr.io/cloud-builders/dart'
    id: 'unit-tests'
    env:
      - 'PATH=/workspace/flutter/bin:$$PATH'
    script: |
      export PATH="/workspace/flutter/bin:$$PATH"

      # Run unit tests with coverage
      flutter test test/unit/ --coverage --reporter=github

      # Run widget tests
      flutter test test/widget/ --coverage --reporter=github

  - name: 'gcr.io/cloud-builders/docker'
    id: 'integration-tests'
    env:
      - 'PATH=/workspace/flutter/bin:$$PATH'
    script: |
      export PATH="/workspace/flutter/bin:$$PATH"

      # Run integration tests in headless mode
      flutter test test/integration/ --coverage --reporter=github

  # ========================================
  # 5. SECURITY SCANNING
  # ========================================
  - name: 'gcr.io/aqua-security/trivy'
    id: 'security-scan'
    args:
      - 'fs'
      - '--format'
      - 'json'
      - '--output'
      - 'security-report.json'
      - '.'

  # ========================================
  # 6. BUILD ANDROID
  # ========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-android'
    env:
      - 'PATH=/workspace/flutter/bin:$$PATH'
      - 'ANDROID_HOME=/opt/android-sdk'
    script: |
      export PATH="/workspace/flutter/bin:$$PATH"
      export ANDROID_HOME="/opt/android-sdk"

      # Accept Android licenses
      yes | flutter doctor --android-licenses

      # Build Android APK
      flutter build apk --release \
        --dart-define=ENVIRONMENT=${_ENVIRONMENT} \
        --dart-define=API_BASE_URL=${_API_BASE_URL} \
        --build-number=${BUILD_ID}

      # Build Android App Bundle
      flutter build appbundle --release \
        --dart-define=ENVIRONMENT=${_ENVIRONMENT} \
        --dart-define=API_BASE_URL=${_API_BASE_URL} \
        --build-number=${BUILD_ID}

  # ========================================
  # 7. BUILD BACKEND SERVICES
  # ========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api-gateway'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/api-gateway:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/api-gateway:latest'
      - '-f'
      - 'docker/api-gateway.Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ml-service'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ml-service:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ml-service:latest'
      - '-f'
      - 'docker/ml-service.Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-video-processor'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/video-processor:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/video-processor:latest'
      - '-f'
      - 'docker/video-processor.Dockerfile'
      - '.'

  # ========================================
  # 8. PUSH DOCKER IMAGES
  # ========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api-gateway'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/api-gateway']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-ml-service'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/ml-service']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-video-processor'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/video-processor']

  # ========================================
  # 9. DEPLOY TO GKE
  # ========================================
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'deploy-to-gke'
    args:
      - 'run'
      - '--filename=k8s/'
      - '--image=gcr.io/$PROJECT_ID/api-gateway:$BUILD_ID'
      - '--image=gcr.io/$PROJECT_ID/ml-service:$BUILD_ID'
      - '--image=gcr.io/$PROJECT_ID/video-processor:$BUILD_ID'
      - '--location=us-central1-a'
      - '--cluster=gait-analysis-cluster'
      - '--namespace=${_NAMESPACE}'

  # ========================================
  # 10. RUN SMOKE TESTS
  # ========================================
  - name: 'gcr.io/cloud-builders/curl'
    id: 'smoke-tests'
    script: |
      # Wait for deployment to be ready
      sleep 60

      # Health check
      curl -f ${_API_BASE_URL}/health || exit 1

      # Basic functionality test
      curl -f ${_API_BASE_URL}/api/v1/status || exit 1

  # ========================================
  # 11. PERFORMANCE TESTING
  # ========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'performance-tests'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/workspace'
      - 'loadimpact/k6'
      - 'run'
      - '/workspace/tests/performance/load-test.js'

  # ========================================
  # 12. DEPLOY TO FIREBASE HOSTING
  # ========================================
  - name: 'gcr.io/$PROJECT_ID/firebase'
    id: 'deploy-firebase'
    args:
      - 'deploy'
      - '--project=${_FIREBASE_PROJECT_ID}'
      - '--only=hosting'

  # ========================================
  # 13. UPDATE MOBILE APP DISTRIBUTION
  # ========================================
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-apk'
    args:
      - 'cp'
      - 'build/app/outputs/flutter-apk/app-release.apk'
      - 'gs://${_BUCKET_NAME}/releases/android/app-release-${BUILD_ID}.apk'

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-aab'
    args:
      - 'cp'
      - 'build/app/outputs/bundle/release/app-release.aab'
      - 'gs://${_BUCKET_NAME}/releases/android/app-release-${BUILD_ID}.aab'

  # ========================================
  # 14. NOTIFICATION & MONITORING
  # ========================================
  - name: 'gcr.io/cloud-builders/curl'
    id: 'notify-slack'
    env:
      - 'SLACK_WEBHOOK=${_SLACK_WEBHOOK}'
    script: |
      curl -X POST "$$SLACK_WEBHOOK" \
        -H "Content-Type: application/json" \
        -d '{
          "text": "🚀 Gait Analysis Pro Build Complete",
          "attachments": [{
            "color": "good",
            "fields": [{
              "title": "Build ID",
              "value": "'${BUILD_ID}'",
              "short": true
            }, {
              "title": "Environment",
              "value": "'${_ENVIRONMENT}'",
              "short": true
            }, {
              "title": "Commit",
              "value": "'${COMMIT_SHA}'",
              "short": true
            }]
          }]
        }'

# ========================================
# BUILD CONFIGURATION
# ========================================
options:
  # Use high CPU machine for faster builds
  machineType: 'E2_HIGHCPU_32'

  # Use SSD for faster I/O
  diskSizeGb: 100

  # Enable detailed logging
  logging: CLOUD_LOGGING_ONLY

  # Set timeout
  timeout: '3600s'

  # Use custom service account
  serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/cloudbuild@$PROJECT_ID.iam.gserviceaccount.com'

# ========================================
# ENVIRONMENT VARIABLES
# ========================================
substitutions:
  _ENVIRONMENT: 'production'
  _API_BASE_URL: 'https://api.gaitanalysis.com'
  _FIREBASE_PROJECT_ID: 'gait-analysis-pro'
  _BUCKET_NAME: 'gait-analysis-releases'
  _NAMESPACE: 'gait-analysis'
  _SLACK_WEBHOOK: ''

# ========================================
# ARTIFACTS & STORAGE
# ========================================
artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/build-artifacts/$BUILD_ID'
    paths:
      - 'build/app/outputs/flutter-apk/*.apk'
      - 'build/app/outputs/bundle/release/*.aab'
      - 'coverage/lcov.info'
      - 'test-results.json'
      - 'security-report.json'

images:
  - 'gcr.io/$PROJECT_ID/api-gateway:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/ml-service:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/video-processor:$BUILD_ID'

# ========================================
# BUILD TRIGGERS
# ========================================
# This file is used by Cloud Build triggers configured in GCP Console:
#
# 1. Continuous Integration Trigger
#    - Branch: ^(main|develop|feature/.*)$
#    - Substitutions: _ENVIRONMENT=development
#
# 2. Production Deployment Trigger
#    - Tag: ^v[0-9]+\.[0-9]+\.[0-9]+$
#    - Substitutions: _ENVIRONMENT=production
#
# 3. Pull Request Trigger
#    - Pull Request to main/develop
#    - Substitutions: _ENVIRONMENT=review